### ISSUE TITLE
Enter and save blood glucose and insulin values

### ISSUE THREAD

**Issue by FreytagDom** [FreytagDom/capstone-project#1]
**Insulin App**

**Value Proposition**
As a diabetic I need the blood glucose value, the amount of carbohydrates and the proper insulin to be able to calculate how much insulin I need to inject.

**Description**

![InsulinApp#1](https://user-images.githubusercontent.com/109357762/190635663-3bf67a63-fd0e-4c08-a2a5-8c7b87633622.svg)

**Acceptance Criteria**

The app should save the entered data locally.
- [x] Enter blood glucose value
- [x] Enter last bolus of insulin
- [x] Enter last basal insulin
- [x] Click Submit to save the data

The data is displayed in a separate card 

**Tasks**

- [x] creat-react-app, create branch
- [x] Create header and h1
- [x] Create label and input
- [x] Add button
- [x] Save values locally

**Comment by ThomasKirst** [comment]
Hi Dominic,

to Value Proposition:

The first user story describes the target and value proposition, therefore you could use "patient" or "diabetic" instead of "user".

My suggestion:
As a diabetic I need to access information about my blood glucose and insulin value, and how many carbohydrates I consumed (?) in order to be able to calculate my insulin need.

Also, your value proposition describes that you intend to calculate something based on the entered data, which is not part of this story, yet, I guess.

About your description:

The excalidraw should be placed under "description".

Regarding Acceptance criteria, you should also create a list of criteria of how the form should work.
Have a look again at the example that Merle provided.

All tasks should have a checkbox at the start of the line:

- [ ] Task 1
- [ ] Task 2
…

Also make sure to change your story title and try to describe your story feature.
Something like "Get and save insulin data" maybe?

Overall, check the formatting of your issue/s.

That´s it so far :)

**Comment by macfrei** [comment]
Hi :) in your `description` you have another Value Proposition? I would only put the scribble under description. Other than that, it looks good 👍 🙂
