### ISSUE TITLE
Calculate insulin quantity

### ISSUE THREAD

**Issue by FreytagDom** [FreytagDom/capstone-project#2]
**Insulin App**

**Value Proposition**

With the app you can enter your blood sugar value, choose which insulin you have, which factor you have to take and how many carbohydrates you want to eat. The app then calculates the amount of insulin to inject.

**Description**

![InsulinApp#2](https://user-images.githubusercontent.com/109357762/190635451-56ad3de9-a465-4012-a9cc-784fa44c7ad9.svg)

**Acceptance Criteria**

The app should calculate the amount of insulin based on the data entered and store it locally.

- [x] Enter blood glucose value
- [x] Enter the carbohydrates you want to consume
- [x] Enter which insulin you are about to inject
- [x] Enter the insulin factor according to the time of day / insulin type
- [x] Click Submit 
- [x] The amount of insulin to be injected and the selected insulin will be displayed.

The data is displayed in a separate card.

**Tasks**

- [x] Create a label for carbohydrates
- [x] Create selection for insulin
- [x] Create selection for daily factor
- [x] Create display for insulin and insulin amount

**Comment by MerleMak** [comment]
Hi Dominic, please use the template properly for your user stories. Also add a meaningful title of each userstory. :)

**Comment by K-Juno** [comment]
Hi Dominic, great project idea!

Just few corrections and suggestions regarding phrasing:

> As a diabetic I need the blood glucose value, **_the amount of_** carbohydrates and **_the proper_** insulin to be able to calculate how much insulin I need to inject.

In the **Description**, you can place your wireframes.

> Acceptance criterion

-> "Acceptance Criteria"

In **Acceptance Criteria**, you should use task list bullet points.

Your **Tasks** header is missing.
