### ISSUE TITLE
Defining the insulin factor

### ISSUE THREAD

**Issue by FreytagDom** [FreytagDom/capstone-project#3]
**Value Proposition**

In this part of the app, you can set and save the factor at the appropriate time of day and the type of insulin so that you do not always have to enter them.

**Description**

![InsulinApp#3](https://user-images.githubusercontent.com/109357762/190639741-c81d792d-fcf9-477b-b40c-3a80677647af.svg)

**Acceptance Criteria**

To save the insulin factor at the appropriate time of day and select it in the main menu: 
- [x] Select insulin type
- [x] Select time of day
- [x] Enter insulin factor 
- [x] Click Submit
- [x] Click on "Start" to go to the home screen
- [x] Click on "Gespeichert" to go to the saved values.
- [x] Click on "Faktor" to go to the page with the insulin factor and determine it.

**Tasks**

- [x] Add  new pages "Insulin factor and saved insulin factor"
- [x] Create a h1 "Insulin factor and saved insulin factor" for the appropriate pages
- [x] Link the new pages
- [x] Create a navigation bar 
- [x] Create an input for the value and a selection of the insulin
- [x] Write a function to save and display the data on an extra page

**Comment by ben-me** [comment]
The benefit promise at the start is always the same in all user stories (it seems). I think we should stick to the template and describe the specific use case that this user story describes.

Your scribbles/concept art is in german while you describe everything in english. It's a better idea to keep everything in the same language so it's not as confusing.

I'd also recommend splitting functions such as "Click on "Home" to go to home screen", "click on "Saved" to go to saved values" and so on into other user stories just for navigation. This also includes moving the tasks (for example "create a navigation bar") into the new story.

These texts: 

> In the app you can enter the insulin data in advance so that you only have to enter the value of the blood sugar and the carbohydrates and select which insulin and which time of day.



> As a diabetic I need the blood glucose value, the amount of carbohydrates and the proper insulin to be able to calculate how much insulin I need to inject.

confuse me as what this story is about. I only understood what the functions should be when reading the acceptance criteria list. Maybe try to restructure so you leave these general descriptions out and only describe each use case of the story.
