### ISSUE TITLE
Input and selection of the values, output of the insulin quantity

### ISSUE THREAD

**Issue by FreytagDom** [FreytagDom/capstone-project#4]
**Insulin App**

**Value Proposition**

As a diabetic, I have to enter and provide certain values/data to get the result of the calculated insulin amount.

**Description**

![InsulinApp#4](https://user-images.githubusercontent.com/109357762/190636392-824449bb-2f6f-4dc2-9bc6-3efc0b89c4d1.svg)

**Acceptance Criteria**

- [x] Enter blood glucose value 
- [x] Enter the amount of carbohydrates you would like to consume.
- [x] Select insulin type 
- [x] Select Insulin Daily Factor
- [x] Click Submit 
- [x] Read the value of the insulin to be injected

**Tasks**
- [x] Change the input fields in the Home Screen so that only the blood glucose value and the carbohydrate information need to be entered
- [x] Add a selection for the insulin with drop down menu
- [x] Add a selection with the insulin daily factor as drop down menu
- [x] The display for the insulin type and amount should be below the Submit button

**Comment by K-Juno** [comment]
Hey Dominic,
falls ich nochmal streng sein darf:
Ich glaube, die Satzstruktur in **Value Proposition** ist deswegen so strikt definiert, weil man damit in einem Satz so klar wie möglich das Ziel und den Grund deiner aktuellen user story erkennen kann.

Vorschlag: As a _**user/diabetic/patient (such's dir aus)**_ I need _**to enter certain values/data**_ to be able to _**get the result of the calculated amount of insulin**_.

**Comment by FreytagDom** [comment]
Hey Juni,
ich bin dir sehr dankbar für dein ehrliches feedback.
