### ISSUE TITLE
Overview of the Stored Data

### ISSUE THREAD

**Issue by FreytagDom** [FreytagDom/capstone-project#5]
**Value Proposition**

As a diabetic, I need an overview of the latest data, to have a history of my entries.

**Description**

![InsulinApp#5](https://user-images.githubusercontent.com/109357762/190919657-ebbfc836-b9a0-4ef6-96a2-c102db6259b4.svg)

**Acceptance Criteria**

- [x] The top card is the most recently added card

- [x] On each entry the date and time of the create is shown

**Tasks**

- [x] Change the design of the "Saved values" page

- [x] Add a date and time of creation to each map entry. 
       Note: Date.now() ,getHours(), getMinutes()

**Comment by NikRoe** [comment]
Hi Dominic,
nice work so far. A few suggestions you might want to include in your user story:

- It would be great if you could keep the sentence structure as discussed in the value proposition:
As a user,
I need ...
to be able to ...
- instead of writing `map` you could stick to `card` 
- you can be a little bit more specific about how the date and time of creation will be determined. Will this be done with a calendar or will there be some other kind of logic to help ensure there is always the correct date and time of creation? (you could do some research on this beforehand)

apart from that: nice work and keep it up!

**Comment by FreytagDom** [comment]
Hi Niklas,
Thanks for your feedback. I have made a few changes. Does it look better now?

**Comment by NikRoe** [comment]
Hey Dominic,
it looks better, but you should change every `map` to `card` (map is a geographic term).

In your value proposition, you should always stick to:
As a user,
I need ...
to be able to ...
How about: "As a diabetic, I need an overview of the latest data, to have a history of my entries".

**Comment by FreytagDom** [comment]
Hey Niklas,
I changed 'map' to 'card' and implemented your suggestion for the value proposition.
